### ISSUE TITLE
Failed to activate the autocomplete-plus package

### ISSUE THREAD

**Issue by haofrank** [atom/autocomplete-plus#1067]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown macOS version
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package 2.42.3

### Stack Trace

Failed to activate the autocomplete-plus package

```
At The module '/Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/text-buffer/node_modules/superstring/build/Release/superstring.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

Error: The module '/Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/text-buffer/node_modules/superstring/build/Release/superstring.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /app.asar/node_modules/text-buffer/node_modules/superstring/index.js:118:15)
    at /app.asar/node_modules/text-buffer/node_modules/superstring/index.js:357:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688158)
    at get_superstring (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:479274)
    at get_NativeTextBuffer (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:479385)
    at new TextBuffer (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:480466)
    at new SubsequenceProvider (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1476850)
    at ProviderManager.toggleDefaultProvider (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:493541)
    at subscriptions.add.atom.config.observe.e (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:491706)
    at Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:334261)
    at Config.observe (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:328743)
    at ProviderManager.initialize (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:491648)
    at AutocompleteManager.initialize (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:641421)
    at Object.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:161679)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3295584)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.17 
atom-ide-ui 0.13.0 
autocomplete-python 1.14.1 
docblockr 0.13.7 
git-blame 1.8.0 
go-debug 1.6.2 
go-plus 6.1.0 
go-signature-statusbar 1.2.3 
```

**Comment by rsese** [comment]
I wonder if this is related to Atom updating to 1.41.0 - can you quit and restart Atom and let us know if you still see the same error?

**Comment by francisnnumbi** [comment]
Same error for me too: this is the stack trace:

Cannot find module 'fuzzaldrin'
Hide Stack Trace
Error: Cannot find module 'fuzzaldrin'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (<embedded>:11:155413)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:61:43)
    at require (<embedded>:11:146745)
    at Object.<anonymous> (/Users/francisnumbi/.atom/packages/autocomplete-plus/lib/autocomplete-manager.js:3:20)
    at Object.<anonymous> (/Users/francisnumbi/.atom/packages/autocomplete-plus/lib/autocomplete-manager.js:801:3)
    at Module.get_Module._compile (<embedded>:11:147429)
    at Object.value [as .js] (<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:72:46)
    at require (<embedded>:11:146745)
    at Object.<anonymous> (/Users/francisnumbi/.atom/packages/autocomplete-plus/lib/main.js:2:29)
    at Object.<anonymous> (/Users/francisnumbi/.atom/packages/autocomplete-plus/lib/main.js:90:3)
    at Module.get_Module._compile (<embedded>:11:147429)
    at Object.value [as .js] (<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (<embedded>:1:688158)
    at Package.requireMainModule (<embedded>:11:3307234)
    at Package.activateNow (<embedded>:11:3295218)
    at measure (<embedded>:11:3294996)
    at Package.measure (<embedded>:11:3292606)
    at activationPromise.activationPromise.Promise (<embedded>:11:3294856)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:11:3294799)
    at PackageManager.activatePackage (<embedded>:11:382285)
    at config.transactAsync (<embedded>:11:381901)
    at Config.transactAsync (<embedded>:11:331549)
    at PackageManager.activatePackages (<embedded>:11:381851)
    at PackageManager.activate (<embedded>:11:381401)
    at t.loadState.then (<embedded>:1:710323)
