### ISSUE TITLE
Me aparece esto, no se como proceder.

### ISSUE THREAD

**Issue by Whynny** [atom/autocomplete-plus#1077]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package 2.42.3

### Stack Trace

Failed to activate the autocomplete-plus package

```
At No se puede encontrar el módulo especificado.
\\?\C:\Users\Whynny1\AppData\Local\atom\app-1.46.0\resources\app.asar.unpacked\node_modules\text-buffer\node_modules\superstring\build\Release\superstring.node

Error: No se puede encontrar el módulo especificado.
\\?\C:\Users\Whynny1\AppData\Local\atom\app-1.46.0\resources\app.asar.unpacked\node_modules\text-buffer\node_modules\superstring\build\Release\superstring.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (<embedded>:11:146745)
    at /app.asar/node_modules/text-buffer/node_modules/superstring/index.js:118:15)
    at /app.asar/node_modules/text-buffer/node_modules/superstring/index.js:357:3)
    at Module.get_Module._compile (<embedded>:11:147429)
    at Object.value [as .js] (<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (<embedded>:1:721712)
    at get_superstring (<embedded>:11:479679)
    at get_NativeTextBuffer (<embedded>:11:479790)
    at new TextBuffer (<embedded>:11:480871)
    at new SubsequenceProvider (<embedded>:14:1469553)
    at ProviderManager.toggleDefaultProvider (<embedded>:14:490345)
    at subscriptions.add.atom.config.observe.e (<embedded>:14:488510)
    at Config.observeKeyPath (<embedded>:11:334676)
    at Config.observe (<embedded>:11:329158)
    at ProviderManager.initialize (<embedded>:14:488452)
    at AutocompleteManager.initialize (<embedded>:11:641776)
    at Object.activate (<embedded>:11:161658)
    at Package.activateNow (<embedded>:11:3287350)
    at measure (<embedded>:11:3286762)
    at Package.measure (<embedded>:11:3284372)
    at activationPromise.activationPromise.Promise (<embedded>:11:3286622)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:11:3286565)
    at PackageManager.activatePackage (<embedded>:11:382700)
    at config.transactAsync (<embedded>:11:382316)
    at Config.transactAsync (<embedded>:11:331964)
    at PackageManager.activatePackages (<embedded>:11:382266)
    at PackageManager.activate (<embedded>:11:381816)
    at t.loadState.then (<embedded>:1:743877)

```

### Commands

```
```

### Non-Core Packages

```
atom-i18n 0.23.0 
```

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

**Comment by revelt** [comment]
The version here seems to be `1.46`, it's not the latest now. Please try a clean reinstall and [try](https://atom.io/releases) `1.47.0`
