### ISSUE TITLE
Problem with Suggestion Providers (Uncaught TypeError: Cannot read property 'length' of undefined)

### ISSUE THREAD

**Issue by tststs** [atom/autocomplete-plus#170]
Uncaught TypeError: Cannot read property 'length' of undefined autocomplete-view.coffee:251

I'm using this example-code for buildSuggestions:

buildSuggestions: ->
        suggestions = []
        suggestions.push new Suggestion(this, word: "async", label: "@async")
        suggestions.push new Suggestion(this, word: "attribute", label: "@attribute")
        suggestions.push new Suggestion(this, word: "author", label: "@author")
        suggestions.push new Suggestion(this, word: "beta", label: "@beta")
        suggestions.push new Suggestion(this, word: "borrows", label: "@borrows")
        suggestions.push new Suggestion(this, word: "bubbles", label: "@bubbles")
        return suggestions

The list populates correctly with these suggestions, but if you confirm the dialog the list disappears and the TypeError occurs.

tststs

**Comment by glaslos** [comment]
Is this related?

1. start atom

**Atom Version**: 1.3.2
**System**: LMDE 2
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.29.0


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/lrist/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:133

TypeError: Cannot read property 'length' of undefined
    at /home/lrist/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:133:7
    at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app.asar/src/config.js:605:7)
    at Config.module.exports.Config.observe (/usr/share/atom/resources/app.asar/src/config.js:141:21)
    at AutocompleteManager.module.exports.AutocompleteManager.handleEvents (/home/lrist/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:131:36)
    at AutocompleteManager.handleEvents (/home/lrist/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1)
    at new AutocompleteManager (/home/lrist/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:55:6)
    at Object.module.exports.getAutocompleteManager (/home/lrist/.atom/packages/autocomplete-plus/lib/main.coffee:29:34)
    at Immediate._onImmediate (/home/lrist/.atom/packages/autocomplete-plus/lib/main.coffee:23:32)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.29.0
file-icons, v1.6.16
go-plus, v3.5.4
minimap, v4.19.0

# Dev
No dev packages
```

**Comment by benogle** [comment]
@glaslos please upgrade to the latest atom version
