### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by basarat** [atom/autocomplete-plus#262]
1. Have autocomplete+ open
![image](https://cloud.githubusercontent.com/assets/874898/6161398/49fb1dea-b2c4-11e4-982d-097f21f4fed0.png)

2. click the close button and select "don't save". Happens everytime

![image](https://cloud.githubusercontent.com/assets/874898/6161408/765488f4-b2c4-11e4-9b6d-e7c01dfef8c8.png)

3. Its these lines in code:

![image](https://cloud.githubusercontent.com/assets/874898/6161413/8a9ffc1c-b2c4-11e4-84e1-a13862d658bf.png)

**Atom Version**: 0.179.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.1.5

### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of undefined

```
At /C:/Users/basaratsyed/.atom/packages/autocomplete-plus/lib/suggestion-list-element.coffee:89

TypeError: Cannot read property 'classList' of undefined
  at autocomplete-suggestion-list.SuggestionListElement.removeActiveClassFromEditor (C:\Users\basaratsyed\.atom\packages\autocomplete-plus\lib\suggestion-list-element.coffee:57:18)
  at autocomplete-suggestion-list.SuggestionListElement.detachedCallback (C:\Users\basaratsyed\.atom\packages\autocomplete-plus\lib\suggestion-list-element.coffee:21:6)
  at atom-pane.PaneElement.itemRemoved (C:\Users\basaratsyed\AppData\Local\atom\app-0.179.0\resources\app\src\pane-element.js:157:29)
  at Emitter.module.exports.Emitter.emit (C:\Users\basaratsyed\AppData\Local\atom\app-0.179.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.removeItem (C:\Users\basaratsyed\AppData\Local\atom\app-0.179.0\resources\app\src\pane.js:398:20)
  at Pane.module.exports.Pane.destroyItem (C:\Users\basaratsyed\AppData\Local\atom\app-0.179.0\resources\app\src\pane.js:457:16)
  at tabs-tab.<anonymous> (C:\Users\basaratsyed\AppData\Local\atom\app-0.179.0\resources\app\node_modules\tabs\lib\tab-bar-view.js:159:24)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\basaratsyed\AppData\Local\atom\app-0.179.0\resources\app\node_modules\jquery\dist\jquery.js:4430:9)
  at space-pen-ul.elemData.handle (C:\Users\basaratsyed\AppData\Local\atom\app-0.179.0\resources\app\node_modules\jquery\dist\jquery.js:4116:28)

```

### Commands

```
     -4:36.1 autocomplete-plus:activate (atom-text-editor.editor.autocomplete-active.is-focused)
     -4:19.8 autocomplete-plus:cancel (atom-text-editor.editor.autocomplete-active.is-focused)
     -4:16.3 typescript:autocomplete (atom-text-editor.editor.autocomplete-active.is-focused)
     -4:16.3 autocomplete-plus:activate (atom-text-editor.editor.autocomplete-active.is-focused)
  3x -4:08.7 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
     -4:02.3 settings-view:open (atom-text-editor.editor.autocomplete-active.is-focused)
     -3:54.4 core:move-up (atom-text-editor.editor.autocomplete-active.is-focused)
     -3:54.1 editor:move-to-end-of-screen-line (atom-text-editor.editor.autocomplete-active.is-focused)
     -3:53.3 typescript:autocomplete (atom-text-editor.editor.autocomplete-active.is-focused)
     -3:53.3 autocomplete-plus:activate (atom-text-editor.editor.autocomplete-active.is-focused)
     -3:48.4 autocomplete-plus:select-next (atom-text-editor.editor.autocomplete-active.is-focused)
     -3:47.9 autocomplete-plus:select-previous (atom-text-editor.editor.autocomplete-active.is-focused)
     -3:41.8 core:move-down (atom-text-editor.editor.autocomplete-active.is-focused)
     -3:41.4 editor:select-to-first-character-of-line (atom-text-editor.editor.autocomplete-active.is-focused)
     -3:41.2 core:delete (atom-text-editor.editor.autocomplete-active.is-focused)
     -3:38.7 core:save (atom-text-editor.editor.autocomplete-active.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "autocomplete-plus": {}
}
```

### Installed Packages

```coffee
# User
atom-typescript, v0.51.0
autocomplete-plus, v2.1.5
color-picker, v1.4.4
linter, v0.11.1
monokai, v0.12.0
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by basarat** [comment]
:zap:

**Comment by JacopoGobbi** [comment]
# This issue occurred again to me

It almost happened randomly:
1. I started writing code
2. I made a mistake (pressed some keys with the palm) by changing place somehow
3. Bug happened

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.17.1


### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list-element.js:271

TypeError: Cannot read property 'classList' of undefined
    at autocomplete-suggestion-list.SuggestionListElement.renderSelectedItem (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list-element.js:271:22)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:168:9)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61
```

### Commands

```
     -8:07.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -8:00.4.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -7:58.1.0 core:save (atom-text-editor.editor.is-focused)
     -3:05.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:34 find-and-replace:show (atom-text-editor.editor.is-focused)
 14x -0:31.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.1.0 find-and-replace:find-previous (atom-text-editor.editor.mini.is-focused)
     -0:01.7.0 core:move-left (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -0:01.6.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {},
  "autocomplete-plus": {
    "confirmCompletion": "tab and enter",
    "suggestionListFollows": "Cursor"
  }
}
```

### Installed Packages

```coffee
# User
highlight-line, v0.10.2
language-haml, v0.20.0
regex-railroad-diagram, v0.7.4
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by benogle** [comment]
@JacopoGobbi your issue will be fixed in the next version of atom (0.202)

**Comment by JacopoGobbi** [comment]
@benogle Thanks for the info!! :+1:

**Comment by parasyte** [comment]
I was directed to this ticket in an error message after hitting escape while autocomplete was opening. (I had Markdown-viewer open and the UI was generally sluggish enough to cancel the auto-completer early.)


**Atom Version**: 0.205.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.17.3


### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list-element.js:274

TypeError: Cannot read property 'classList' of undefined
    at autocomplete-suggestion-list.SuggestionListElement.renderSelectedItem (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list-element.js:274:22)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:168:9)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61
```

### Commands

```
     -0:09.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:09.1.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:08.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:08.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:08.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:08.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:08.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:08.7.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:08.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:08.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:08.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:08.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:08.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:08.3.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:01.6.0 core:move-up (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:01.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "metrics",
      "welcome",
      "minimap"
    ],
    "themes": [
      "atom-soda-dark-ui",
      "pretty-pastels-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-soda-dark-ui, v0.9.0
auto-detect-indentation, v0.4.2
file-icons, v1.5.6
highlight-selected, v0.9.3
language-lua, v0.9.3
pretty-pastels-syntax, v0.1.4
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by andreialecu** [comment]
Atom 0.207.0 here and I just got this. I was editing a .jade file if that matters, but it occured randomly.



**Atom Version**: 0.207.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.17.3


### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of undefined

```
At C:\Users\...\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\autocomplete-plus\lib\suggestion-list-element.js:274

TypeError: Cannot read property 'classList' of undefined
  at autocomplete-suggestion-list.SuggestionListElement.renderSelectedItem (C:\Users\...\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\autocomplete-plus\lib\suggestion-list-element.js:274:22)
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (C:\Users\...\AppData\Local\atom\app-0.207.0\resources\app.asar\src\view-registry.js:168:9)
  at C:\Users\...\AppData\Local\atom\app-0.207.0\resources\app.asar\src\view-registry.js:3:61

```

### Commands

```
     -5:03.4.0 core:paste (atom-text-editor.editor.is-focused)
  2x -5:02.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -4:58.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -4:58 core:backspace (atom-text-editor.editor.is-focused)
     -4:57.8.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -4:54.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:53.3.0 core:copy (atom-text-editor.editor.is-focused)
  4x -4:51.1.0 core:undo (atom-text-editor.editor.is-focused)
     -0:27.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:26.8.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:26.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:23.4.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:21.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:11.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:11.2.0 core:move-left (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:11.2.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.27.12
atom-terminal, v0.8.0
docblockr, v0.7.2
file-icons, v1.5.7
highlight-selected, v0.9.3
jsformat, v0.9.0
language-jade, v0.4.0
linter, v0.12.6
linter-jshint, v0.1.6
minimap, v4.9.4
project-manager, v1.15.10
zentabs, v0.8.4

# Dev
No dev packages
```

**Comment by cgomezmendez** [comment]
I was editing the html ninja template when it suddenly happen.

**Atom Version**: 0.208.0
**System**: Ubuntu 15.04
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.17.3


### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of undefined

```
At /opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list-element.js:274

TypeError: Cannot read property 'classList' of undefined
  at autocomplete-suggestion-list.SuggestionListElement.renderSelectedItem (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list-element.js:274:22)
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/opt/atom/resources/app.asar/src/view-registry.js:168:9)
  at /opt/atom/resources/app.asar/src/view-registry.js:3:61

```

### Commands

```
     -0:10.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:10.5.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:10.3.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:10.1.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:09.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:09.3.0 core:move-up (atom-text-editor.editor.is-focused)
 20x -0:09.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:07.3.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:06.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:05.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:05.6.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -0:05.4.0 core:move-left (atom-text-editor.editor.is-focused)
 12x -0:04.6.0 core:select-right (atom-text-editor.editor.is-focused)
  2x -0:03.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.0 core:move-left (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:01.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "go-plus",
      "vim-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jinja2, v0.5.0
autocomplete-python, v0.4.2
language-html, v0.40.0
linter, v0.12.7
linter-flake8, v1.4.2
linter-pylint, v0.2.2
linter-tidy, v1.0.1
python-isort, v0.0.7
tabs-to-spaces, v0.11.0
tidy-markdown, v1.0.0

# Dev
No dev packages
```

**Comment by tanakh** [comment]
I am writing small single Haskell file and suddenly it happened.
My system is Windows 8.1.

**Atom Version**: 0.209.0
**System**: Unknown Windows Version
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.17.3


### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of undefined

```
At C:\Users\tanakh\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\autocomplete-plus\lib\suggestion-list-element.js:274

TypeError: Cannot read property 'classList' of undefined
  at autocomplete-suggestion-list.SuggestionListElement.renderSelectedItem (C:\Users\tanakh\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\autocomplete-plus\lib\suggestion-list-element.js:274:22)
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (C:\Users\tanakh\AppData\Local\atom\app-0.209.0\resources\app.asar\src\view-registry.js:168:9)
  at C:\Users\tanakh\AppData\Local\atom\app-0.209.0\resources\app.asar\src\view-registry.js:3:61

```

### Commands

```
     -0:07.4.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:07.3.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:07.2.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -0:07.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:06.8.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -0:06.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:06.4.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:06.2.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:06.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:05.6.0 core:move-down (atom-text-editor.editor.is-focused)
  6x -0:05.5.0 core:move-left (atom-text-editor.editor.is-focused)
  4x -0:04.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.7.0 core:move-up (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:03.7.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:02.5.0 core:move-up (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:02.5.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.4.4
haskell-ghc-mod, v0.7.5
ide-haskell, v0.5.11
language-haskell, v1.1.1

# Dev
No dev packages
```

**Comment by benogle** [comment]
This will be fixed in the next version of atom.

**Comment by arjun-u** [comment]
Windows 7, Atom

<pre>
TypeError: Cannot read property 'classList' of undefined
    at autocomplete-suggestion-list.SuggestionListElement.renderSelectedItem (C:\Users\arjun.RZT\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\autocomplete-plus\lib\suggestion-list-element.js:274:22)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (C:\Users\arjun.RZT\AppData\Local\atom\app-0.209.0\resources\app.asar\src\view-registry.js:168:9)
    at C:\Users\arjun.RZT\AppData\Local\atom\app-0.209.0\resources\app.asar\src\view-registry.js:3:61
</pre>

**Comment by impinball** [comment]
@basarat Can you repro the above? (I only see random crashes, no pattern, so I don't know where to look)

**Comment by basarat** [comment]
@impinball nope. To be honest : Hasn't happened to me since the *first time* this issue got closed : https://github.com/atom/autocomplete-plus/issues/262#issuecomment-74014667

**Comment by stevekuznetsov** [comment]
# Please Re-Open
Happened to me. Stack trace:
```
TypeError: Cannot read property 'classList' of undefined
    at autocomplete-suggestion-list.SuggestionListElement.renderSelectedItem (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list-element.js:274:22)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app.asar/src/view-registry.js:168:9)
    at /usr/share/atom/resources/app.asar/src/view-registry.js:3:61
```

**Comment by benogle** [comment]
@stevekuznetsov this is not out yet. It will be out in atom 1.0.3

**Comment by benogle** [comment]
@stevekuznetsov What version of atom are you using?
