### ISSUE TITLE
Error while editing

### ISSUE THREAD

**Issue by lombardi-gux** [atom/autocomplete-plus#451]
1. was editing a multiline selection in js file

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.14.2

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/stevelombardi/.atom/packages/autocomplete-plus/lib/suggestion-list-element.coffee:96

TypeError: Cannot read property '0' of undefined
  at autocomplete-suggestion-list.SuggestionListElement.updateDescription (/Users/stevelombardi/.atom/packages/autocomplete-plus/lib/suggestion-list-element.coffee:96:36)
  at autocomplete-suggestion-list.SuggestionListElement.renderItems (/Users/stevelombardi/.atom/packages/autocomplete-plus/lib/suggestion-list-element.coffee:184:6)
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:168:9)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61

```

### Commands

```
     -1:13.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:13.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:10.8.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:26.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:26.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:26.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:24.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:23.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:23.6.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:20.1.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:18.2.0 editor:split-selections-into-lines (atom-text-editor.editor.is-focused)
  2x -0:13.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:07.6.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:06.6.0 core:copy (atom-text-editor.editor.is-focused)
     -0:06.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:00.3.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "deprecation-cop",
      "preview-tabs",
      "autocomplete-snippets",
      "gulp-control",
      "SFTP-deployment",
      "autoprefixer",
      "linter-csslint"
    ],
    "themes": [
      "isotope-ui",
      "inspired-github"
    ]
  },
  "autocomplete-plus": {
    "confirmCompletion": "enter"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-beautify, v0.27.1
atom-color-highlight, v3.0.9
autocomplete-css, v0.7.2
autocomplete-html, v0.7.1
autocomplete-paths, v1.0.2
autocomplete-plus, v2.14.2
color-picker, v1.7.0
emmet, v2.3.9
file-icons, v1.5.5
inspired-github, v0.5.2
isotope-ui, v2.2.0
linter, v0.12.2
linter-jscs, v1.11.0
linter-jshint, v0.1.4
linter-scss-lint, v0.0.14
project-manager, v1.15.5
project-palette-finder, v2.4.17
selection-counter, v0.1.1
tag, v0.2.3

# Dev
No dev packages
```

**Comment by benogle** [comment]
This should be fixed by the latest ac+ release: 2.15.0. Let me know if it isnt!
