### ISSUE TITLE
Uncaught Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by devrchancay** [atom/autocomplete-plus#472]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.199.0
**System**: linux 3.16.0-37-generic
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.17.0

### Stack Trace

Uncaught Error: Cannot find module 'semver'

```
At module.js:330

Error: Cannot find module 'semver'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/opt/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/universo/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:3:10)
  at Object.<anonymous> (/home/universo/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/opt/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.module.exports.getAutocompleteManager (/home/universo/.atom/packages/autocomplete-plus/lib/main.coffee:128:29)
  at Immediate._onImmediate (/home/universo/.atom/packages/autocomplete-plus/lib/main.coffee:123:32)
  at processImmediate [as _immediateCallback] (timers.js:369:17)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.17.0
emmet-atom, v2.3.9
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
Did you build or install your copy of Atom?

**Comment by devrchancay** [comment]
install

**Comment by benogle** [comment]
@devrchancay Was this a one time thing? Or are you seeing it often? Are you on the latest version of atom?

**Comment by benogle** [comment]
Also, can you `ls ~/.atom/packages` and paste the output for me?

**Comment by AgentAntelope** [comment]
Hey, I know this is closed, but I'm seeing this exception.

stack trace: 
```
module.js:338
Hide Stack Trace
Error: Cannot find module 'semver'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/opt/homebrew-cask/Caskroom/atom/1.0.11/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.0.11/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/alexs/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:3:10)
    at Object.<anonymous> (/Users/alexs/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1)
    at Module._compile (/opt/homebrew-cask/Caskroom/atom/1.0.11/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/1.0.11/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.0.11/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.getAutocompleteManager (/Users/alexs/.atom/packages/autocomplete-plus/lib/main.coffee:28:29)
    at Immediate._onImmediate (/Users/alexs/.atom/packages/autocomplete-plus/lib/main.coffee:23:32)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

Atom version 1.5.3

Packages: 
auto-update-packages
autocomplete-plus
blame
block-travel
cucumber
file-icons
highlight-selected
language-gherkin
linter
linter-ruby
pretty-json
rails-rspec
sort-lines

**Comment by lee-dohm** [comment]
Are you sure you're on v1.5.3? Homebrew seems to think you're on v1.0.11?

**Comment by AgentAntelope** [comment]
That's just the directory I'm installed in (doesn't change when I upgrade inside atom). `atom -v` returns 1.5.3.

**Comment by lee-dohm** [comment]
Sorry, I should have read a little further to this in the stack trace:

```
/Users/alexs/.atom/packages/autocomplete-plus/
```

It appears that you have a copy of autocomplete-plus manually installed. Please uninstall the copy that is in your `~/.atom/packages` directory to allow the copy built into Atom to take precedence.

**Comment by AgentAntelope** [comment]
That fixed it for me! I assume that's from before autocomplete-plus was absorbed into atom. Thank you very much for your time.

**Comment by lee-dohm** [comment]
You're welcome. I'm glad it's fixed :grinning:
