### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tokens' of undefined

### ISSUE THREAD

**Issue by selasiehanson** [atom/autocomplete-plus#478]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.17.1

### Stack Trace

Uncaught TypeError: Cannot read property 'tokens' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:294

TypeError: Cannot read property 'tokens' of undefined
  at SymbolStore.module.exports.SymbolStore.operateOnTokensInBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:294:32)
  at SymbolStore.module.exports.SymbolStore.addTokensInBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:272:19)
  at SymbolProvider.module.exports.SymbolProvider.buildSymbolList (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-provider.js:423:31)
  at SymbolProvider.buildSymbolList (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-provider.js:3:61)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-provider.js:413:24
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47

```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "gocode",
      "linter-golint",
      "atom-beautify",
      "autocomplete",
      "atom-terminal",
      "terminal-panel",
      "atom-terminal-panel",
      "jsformat"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "autocomplete-plus": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-handlebars, v0.5.0
atom-typescript, v4.5.0
color-picker, v1.7.0
emmet, v2.3.10
go-plus, v3.3.11
jshint, v1.3.7
language-handlebars, v0.2.0
language-rust, v0.4.3
linter, v0.12.6
linter-rust, v0.0.13
racer, v0.11.0
react, v0.11.8
rust-api-docs-helper, v0.5.1
vim-mode, v0.48.0

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
I am also experiencing this. I was unable to save and/or copy, and so lost my changes.

I had opened Split panels, with `Split: Right` command, and was typing JavaScript.

**Atom Version**: 0.201.0
**System**: Microsoft Windows 8.1
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.17.1


### Stack Trace

Uncaught TypeError: Cannot read property 'tokens' of undefined

```
At C:\Users\Glavin\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:683

TypeError: Cannot read property 'tokens' of undefined
    at SymbolStore.module.exports.SymbolStore.operateOnTokensInBufferRange (C:\Users\Glavin\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\autocomplete-plus\lib\symbol-store.js:294:32)
    at SymbolStore.module.exports.SymbolStore.removeTokensInBufferRange (C:\Users\Glavin\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\autocomplete-plus\lib\symbol-store.js:276:19)
    at C:\Users\Glavin\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\autocomplete-plus\lib\symbol-provider.js:117:31
    at Emitter.module.exports.Emitter.emit (C:\Users\Glavin\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (C:\Users\Glavin\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:503:20)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (C:\Users\Glavin\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:717:16)
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\Glavin\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:681:14)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\Glavin\AppData\Local\atom\app-0.201.0\resources\app.asar\src\text-editor.js:1132:26)
    at C:\Users\Glavin\AppData\Local\atom\app-0.201.0\resources\app.asar\src\text-editor.js:765:24
    at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\Glavin\AppData\Local\atom\app-0.201.0\resources\app.asar\src\text-editor.js:1954:18)
```

### Commands

```
  2x -0:38.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:30.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:27.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:27.5.0 pane:split-right (atom-text-editor.editor)
     -0:16.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:15.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:13 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:12.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:11.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:10.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -0:10 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by obiwanakin** [comment]
I also have this! Like @Glavin001, I also split a panel to the right. However, I'm writing python. Here's my stack trace: 

```
TypeError: Cannot read property 'tokens' of undefined
  at SymbolStore.module.exports.SymbolStore.operateOnTokensInBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:294:32)
  at SymbolStore.module.exports.SymbolStore.removeTokensInBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:276:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-provider.js:117:31
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:503:20)
  at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:717:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:681:14)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1132:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:765:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1954:18)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1924:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:763:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:726:21)
  at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher.js:142:26
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:678:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1132:26)
  at BracketMatcher.module.exports.BracketMatcher.insertNewline (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher.js:139:21)
  at TextEditor.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher.js:3:61)
  at TextEditor.object.(anonymous function) [as insertNewline] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:76:20)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.editor:newline (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:593:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:305:34
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:678:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1132:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:304:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)
```

**Comment by bradens** [comment]
Same here, split right, typing scss. 

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.17.1


### Stack Trace

Uncaught TypeError: Cannot read property 'tokens' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:683

TypeError: Cannot read property 'tokens' of undefined
  at SymbolStore.module.exports.SymbolStore.operateOnTokensInBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:294:32)
  at SymbolStore.module.exports.SymbolStore.removeTokensInBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:276:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-provider.js:117:31
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:503:20)
  at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:717:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:681:14)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1132:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:765:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1954:18)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1924:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:763:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:726:21)
  at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher.js:142:26
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:678:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1132:26)
  at BracketMatcher.module.exports.BracketMatcher.insertNewline (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher.js:139:21)
  at TextEditor.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher.js:3:61)
  at TextEditor.object.(anonymous function) [as insertNewline] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:76:20)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.editor:newline (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:593:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:305:34
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:678:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1132:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:304:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
  8x -0:14.9.0 atomic-emacs:previous-line (atom-text-editor.editor.kill-ring.is-focused)
  3x -0:14.4.0 atomic-emacs:next-line (atom-text-editor.editor.kill-ring.is-focused)
  8x -0:14 atomic-emacs:previous-line (atom-text-editor.editor.kill-ring.is-focused)
  5x -0:12.3.0 atomic-emacs:next-line (atom-text-editor.editor.kill-ring.is-focused)
  5x -0:11.2.0 atomic-emacs:previous-line (atom-text-editor.editor.kill-ring.is-focused)
     -0:10.4.0 atomic-emacs:set-mark (atom-text-editor.editor.kill-ring.is-focused)
 14x -0:10.4.0 atomic-emacs:next-line (atom-text-editor.editor.kill-ring.is-focused)
     -0:09.4.0 editor:move-to-end-of-line (atom-text-editor.editor.kill-ring.is-focused)
     -0:09.1.0 atomic-emacs:previous-line (atom-text-editor.editor.kill-ring.is-focused)
     -0:09.0 editor:move-to-end-of-line (atom-text-editor.editor.kill-ring.is-focused)
     -0:08.8.0 core:cut (atom-text-editor.editor.kill-ring.is-focused)
  3x -0:08.3.0 core:backspace (atom-text-editor.editor.kill-ring.is-focused)
  2x -0:07.3.0 atomic-emacs:next-line (atom-text-editor.editor.kill-ring.is-focused)
     -0:06.7.0 editor:newline (atom-text-editor.editor.kill-ring.is-focused)
  4x -0:04.7.0 core:backspace (atom-text-editor.editor.kill-ring.is-focused)
     -0:01.2.0 editor:newline (atom-text-editor.editor.kill-ring.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      "build"
    ],
    "themes": [
      "quantum-ui",
      "base16-tomorrow-dark-theme"
    ],
    "useReactEditor": true,
    "disabledPackages": [
      "editor-stats",
      "toggle-tabs",
      "term2",
      "sublime-tabs",
      "tabs",
      "emacs-mode",
      "terminal-status",
      "linter-jshint"
    ]
  },
  "autocomplete-plus": {
    "confirmCompletion": "enter",
    "includeCompletionsFromAllBuffers": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.27.6
atom-lint, v0.20.1
atomic-emacs, v0.5.1
custom-title, v0.7.1
emacs-mode, v0.0.29
language-haml, v0.20.0
linter, v0.12.6
linter-coffeelint, v0.2.4
linter-haml, v0.4.0
linter-rubocop, v0.2.7
linter-scss-lint, v1.0.4
linter-tidy, v1.0.1
pane-info, v1.0.0
pretty-json, v0.3.3
quantum-ui, v0.2.2
react, v0.11.8
tag, v0.3.0

# Dev
No dev packages
```

**Comment by obiwanakin** [comment]
Nice!

**Comment by nathansobo** [comment]
@benogle Is there any way that a dead editor could have been left in the array associated with the buffer? We really need some better system for making assertions and reporting on inconsistent states so we can fix these issues instead of glossing them over.

**Comment by nathansobo** [comment]
@Glavin001 @bradens @obiwanakin Did you folks remember if closed the original editor after splitting rightward or if you left it open. Also, did you do any saving or changing of file paths?
