### ISSUE TITLE
Uncaught TypeError: Cannot read property 'displayBuffer' of undefined

### ISSUE THREAD

**Issue by vgpena** [atom/autocomplete-plus#488]
1. Disabled autocomplete-plus
2. Opened a file, navigated to a place in the file, and pressed the Enter key

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.17.3

### Stack Trace

Uncaught TypeError: Cannot read property 'displayBuffer' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:755

TypeError: Cannot read property 'displayBuffer' of undefined
  at SymbolStore.module.exports.SymbolStore.getTokenizedLines (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:336:20)
  at SymbolStore.module.exports.SymbolStore.operateOnTokensInBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:281:29)
  at SymbolStore.module.exports.SymbolStore.removeTokensInBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:276:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-provider.js:117:31
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:592:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:532:12)
  at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:452:43)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:730:31
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:775:29
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:750:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1136:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:769:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1954:43)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1928:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:767:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:727:21)
  at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at TextEditor.module.exports.TextEditor.insertNewline (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:748:19)
  at TextEditor.object.(anonymous function) [as insertNewline] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.editor:newline (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:593:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:305:34
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:750:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1136:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:304:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -2:21 core:move-right (atom-text-editor.editor.is-focused)
  4x -2:19.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:15.2.0 editor:newline-above (atom-text-editor.editor.is-focused)
     -2:14.7.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:12.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:08.4.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -2:07.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:06.4.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:28.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:26.5.0 core:save (atom-text-editor.editor.is-focused)
     -1:22.2.0 pane:split-right (atom-text-editor.editor.is-focused)
     -1:21.2.0 core:close (atom-text-editor.editor.is-focused)
     -0:17.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:15.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:15.9.0 core:cancel (atom-text-editor.editor.is-focused)
  2x -0:14.3.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "autocomplete-plus"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-javascript-better, v1.0.0
react, v0.7.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Ran into this myself today, while trying to reproduce this: https://github.com/atom/atom/issues/5905#issuecomment-108429031. Happened after I closed a split view and started editing a part of text which had some syntax error highlighted.


----

**Atom Version**: 0.209.0-b903302
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.17.3


### Stack Trace

Uncaught TypeError: Cannot read property 'displayBuffer' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:745

TypeError: Cannot read property 'displayBuffer' of undefined
  at SymbolStore.module.exports.SymbolStore.getTokenizedLines (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:336:20)
  at SymbolStore.module.exports.SymbolStore.operateOnTokensInBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:281:29)
  at SymbolStore.module.exports.SymbolStore.removeTokensInBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:276:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-provider.js:117:31
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:594:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:534:12)
  at TextBuffer.module.exports.TextBuffer.delete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:633:19)
  at Selection.module.exports.Selection.deleteSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:560:37)
  at Selection.module.exports.Selection.backspace (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:489:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:771:26
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:787:29
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:740:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1148:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:781:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1978:18)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1948:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:779:19)
  at TextEditor.module.exports.TextEditor.backspace (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:770:19)
  at TextEditor.object.(anonymous function) [as backspace] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.core:backspace (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:427:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:307:34
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:740:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1148:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:306:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -2:17.8.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -2:16.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:13.4.0 core:select-all (atom-text-editor.editor.is-focused)
     -2:13 core:backspace (atom-text-editor.editor.is-focused)
     -2:12 core:undo (atom-text-editor.editor.is-focused)
     -2:08.3.0 core:save (atom-text-editor.editor.is-focused)
     -2:00.1.0 pane:split-right (atom-text-editor.editor.is-focused)
     -0:49.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:38.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:36 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:30.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:26.5.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  3x -0:26.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.6.0 core:close (atom-text-editor.editor.is-focused)
  3x -0:00.9.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "autocomplete-plus": {}
}
```

### Installed Packages

```coffee
# User
linter, v0.12.7
linter-php, v0.0.15

# Dev
No dev packages
```
