### ISSUE TITLE
:bug: Error when overriding open files

### ISSUE THREAD

**Issue by acontreras89** [atom/autocomplete-plus#491]
Using command `Core: Save As` and overriding a file that is already open causes the following error:
`TypeError: Cannot read property 'tokens' of undefined`

**Comment by benogle** [comment]
* Can you paste in the entire error report from the red popup?
* Did you rename this file before saving as?
* Is this consistently repeatable for you?

**Comment by acontreras89** [comment]
Sorry @benogle, wanted to copy it but looks like I didn't :sweat_smile: 
There you go:
```
TypeError: Cannot read property 'tokens' of undefined
  at SymbolStore.module.exports.SymbolStore.operateOnTokensInBufferRange (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:294:32)
  at SymbolStore.module.exports.SymbolStore.removeTokensInBufferRange (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:276:19)
  at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/symbol-provider.js:117:31
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:503:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:470:12)
  at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:439:21
  at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:678:18)
  at TextBuffer.module.exports.TextBuffer.setTextViaDiff (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:414:19)
  at TextBuffer.module.exports.TextBuffer.reload (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:998:12)
  at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1122:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:430:40
  at _fulfilled (/usr/share/atom/resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/usr/share/atom/resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/usr/share/atom/resources/app.asar/node_modules/q/q.js:756:13)
  at /usr/share/atom/resources/app.asar/node_modules/q/q.js:564:44
  at flush (/usr/share/atom/resources/app.asar/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:357:13)
```

I get this error every time. To reproduce:

* Open two files
* On one of them, use `Core: Save As` command
* In the Save As dialog, navigate to the other open file and select Save
* Select Replace, confirming the action

**Comment by benogle** [comment]
Thanks for the steps.
