### ISSUE TITLE
Failed to load the autocomplete-gocode package

### ISSUE THREAD

**Issue by dougnukem** [atom/autocomplete-plus#497]
[Enter steps to reproduce below:]

1. Launched Atom 0.207.0
2. Saw this error with the autocomplete-gocode package

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.17.3

### Stack Trace

Failed to load the autocomplete-gocode package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/ddaniels/.atom/packages/autocomplete-plus/lib/simple-select-list-view.coffee:4:199)
    at /Users/ddaniels/.atom/packages/autocomplete-plus/lib/simple-select-list-view.coffee:17:5
    at Object.<anonymous> (/Users/ddaniels/.atom/packages/autocomplete-plus/lib/simple-select-list-view.coffee:176:5)
    at Object.<anonymous> (/Users/ddaniels/.atom/packages/autocomplete-plus/lib/simple-select-list-view.coffee:180:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-golint",
      "linter",
      "go-format"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "autocomplete-plus": {
    "autoActivationDelay": 1
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v0.4.2
autocomplete-gocode, v0.5.0
color-picker, v2.0.4
command-logger, v0.23.0
editor-stats, v0.17.0
file-icons, v1.5.7
go-plus, v3.3.11
jshint, v1.3.7
markdown-format, v2.5.1
minimap, v4.9.4
monokai, v0.14.0
react, v0.12.0
script, v2.23.0
smarter-delete-line, v1.1.2
travis-ci-status, v0.15.0
vim-mode, v0.51.0

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
Uninstall autocomplete-gocode. go-plus includes the same functionality.
