### ISSUE TITLE
Uncaught Error: Cannot find module 'minimatch'

### ISSUE THREAD

**Issue by TCambs** [atom/autocomplete-plus#565]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.9
**System**: Mac OS X 10.11
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.19.0

### Stack Trace

Uncaught Error: Cannot find module 'minimatch'

```
At module.js:330

Error: Cannot find module 'minimatch'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Users/taylor/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at AutocompleteManager.module.exports.AutocompleteManager.isCurrentFileBlackListed (/Users/taylor/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:576:21)
    at AutocompleteManager.isCurrentFileBlackListed (/Users/taylor/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Users/taylor/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:223:16)
    at /Users/taylor/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
  7x -0:04.3.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by benogle** [comment]
This is really strange. Are you using a local version of autocomplete-plus?

**Comment by TCambs** [comment]
I shouldn't be. I haven't messed with any of Atoms config files outside of installing packages/themes

**Comment by benogle** [comment]
Was this a one time thing or does it happen consistently?

**Comment by TCambs** [comment]
Happens overtime I open Atom... I haven't found anyway to fix it myself.

**Comment by ihuguowei** [comment]
I meet the same problem.
![image](https://cloud.githubusercontent.com/assets/3097742/11332125/bbf0500a-91fd-11e5-87b4-9b390f01da25.png)

**Comment by thomasjo** [comment]
@ihuguowei Your problem looks completely unrelated to this issue. This issue is specifically related to the bundled autocomplete-plus package for Atom, whereas you seem to be working in a more general Node.js context.

**Comment by ihuguowei** [comment]
@thomasjo thx, I install all the relative module.It can work well.

**Comment by ihuguowei** [comment]
@thomasjo sorry.my fault.
