### ISSUE TITLE
Uncaught TypeError: this.metadataByPath.get is not a function

### ISSUE THREAD

**Issue by robjac** [atom/autocomplete-plus#589]
[Enter steps to reproduce below:]

1. Tried to save... happens with any file type. 

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.19.1

### Stack Trace

Uncaught TypeError: this.metadataByPath.get is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:71

TypeError: this.metadataByPath.get is not a function
  at Symbol.addInstance (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:71:38)
  at SymbolStore.module.exports.SymbolStore.addSymbol (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:323:21)
  at SymbolStore.module.exports.SymbolStore.addToken (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:259:16)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:3:61
  at SymbolStore.module.exports.SymbolStore.operateOnTokensInBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:298:13)
  at SymbolStore.module.exports.SymbolStore.addTokensInBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:276:19)
  at SymbolProvider.module.exports.SymbolProvider.buildSymbolList (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-provider.js:417:31)
  at SymbolProvider.buildSymbolList (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-provider.js:3:61)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-provider.js:407:24
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47

```

### Commands

```
     -1:25.3.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -1:20.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:19.5.0 tidal:eval (atom-text-editor.editor.is-focused)
  7x -1:18.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:16.9.0 tidal:eval (atom-text-editor.editor.is-focused)
  4x -1:15.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:13.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:13.9.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -1:13.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:10.9.0 project-find:show (atom-text-editor.editor.is-focused)
     -1:07.4.0 highlight-line:toggle-background (atom-text-editor.editor.mini.is-focused)
     -1:05.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:05.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:03.4.0 tidal:hush (atom-text-editor.editor.is-focused)
     -0:46.2.0 settings-view:open (atom-text-editor.editor.is-focused)
  6x -0:13.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "neon-syntax"
    ],
    "disabledPackages": [
      "tree-view-breadcrumb",
      "supercollider",
      "line-count",
      "highlight-css-color",
      "atom-jade",
      "processing-language",
      "language-supercollider",
      "vim-mode"
    ],
    "projectHome": "~/DEV/"
  },
  "autocomplete-plus": {
    "confirmCompletion": "tab and enter"
  }
}
```

### Installed Packages

```coffee
# User
Package-Upgrader, v0.3.1
angularjs, v0.3.0
auto-indent, v0.5.0
auto-update-packages, v1.0.0
autocomplete-paths, v1.0.2
color-gutter, v0.4.1
color-picker, v2.0.13
css-color-underline, v1.0.1
emmet, vundefined
highlight-column, v0.5.0
highlight-line, v0.11.0
language-jade, v0.6.2
linter, vundefined
linter-csslint, v1.1.0
linter-eslint, v3.1.1
linter-gjslint, v0.0.5
linter-jscs, v3.1.1
minimap, v4.13.4
minimap-bookmarks, v0.1.0
minimap-color-highlight, v4.1.4
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
neon-syntax, v0.3.5
pigments, v0.15.0
project-manager, v2.6.1
react, v0.12.10
settings-view, v0.225.0
tidal, v2.1.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hey @robjac, can you please see if this still happens in safe mode (`atom --safe`)?  Thanks

**Comment by robjac** [comment]
So far it hasn't done it in safe mode.

**Comment by 50Wliu** [comment]
Ok, nice to hear!  In that case, you can try using the [package-cop](https://atom.io/packages/package-cop) package to find out which package is causing this exception.

**Comment by daralthus** [comment]
`apm uninstall autocomplete-plus` solves the issue for me, after that atom started to use the bundled version
