### ISSUE TITLE
this.metadataByPath.get  ??

### ISSUE THREAD

**Issue by danjm75** [atom/autocomplete-plus#591]
I just installed Atom and keep getting these . Not sure what is up.[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.19.1

### Stack Trace

Uncaught TypeError: this.metadataByPath.get is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:34

TypeError: this.metadataByPath.get is not a function
  at Symbol.countForBuffer (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:34:38)
  at Symbol.clearForBuffer (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:48:26)
  at SymbolStore.module.exports.SymbolStore.clear (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:201:18)
  at SymbolProvider.module.exports.SymbolProvider.buildSymbolList (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-provider.js:416:24)
  at SymbolProvider.buildSymbolList (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-provider.js:3:61)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-provider.js:407:24
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47

```

### Commands

```
     -3:51.2.0 core:save (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:22.6.0 application:add-project-folder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.13
javascript-snippets, v1.0.0

# Dev
No dev packages
```

**Comment by thomasjo** [comment]
Hmm, weird. Are you able to reproduce this in safe mode? `atom --safe`

**Comment by benogle** [comment]
What kind of files / tabs do you have open? Just code files? What kind of code files?

**Comment by danjm75** [comment]
Sorry fellow humans, I scrapped atom and am now using brackets. I'm kind of in a time crunch now so I couldn't spend the time I wanted with it. I actually want to use sublime.  I just don't know if sublime is completely "open" if you don't buy it? I appreciate your replies and truely apologize for taking your time. Happy coding!
