### ISSUE TITLE
Uncaught TypeError: this.editor.onDidChangeCursorPosition is not a function

### ISSUE THREAD

**Issue by pepri** [atom/autocomplete-plus#614]
[Enter steps to reproduce below:]

1. Open PlantUML viewer (plantuml-viewer).
2. Focus the opened tab.

**Atom Version**: 1.2.0
**System**: Debian GNU/Linux
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.23.0

### Stack Trace

Uncaught TypeError: this.editor.onDidChangeCursorPosition is not a function

```
At /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:139

TypeError: this.editor.onDidChangeCursorPosition is not a function
    at AutocompleteManager.module.exports.AutocompleteManager.updateCurrentEditor (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:139:48)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /usr/share/atom/resources/app.asar/src/pane-container.js:333:27
    at Pane.module.exports.Pane.observeActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:196:7)
    at /usr/share/atom/resources/app.asar/src/pane-container.js:331:42
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at PaneContainer.module.exports.PaneContainer.setActivePane (/usr/share/atom/resources/app.asar/src/pane-container.js:196:22)
    at Pane.module.exports.Pane.activate (/usr/share/atom/resources/app.asar/src/pane.js:619:15)
    at space-pen-div.<anonymous> (/home/peterp/.atom/packages/plantuml-viewer/lib/plantuml-viewer-view.js:43:48)
    at space-pen-div.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:06.0 core:paste (atom-text-editor.editor.is-focused)
  3x -1:04.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:01.5.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -1:01.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:59.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -0:56.2.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:52.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:45.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:45.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:43 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:43 plantuml-viewer:toggle (atom-text-editor.editor)
     -0:27.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:22.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:21.5.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:21.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:10.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "symbols-view",
      "nbsp-detect",
      "terminal-panel"
    ],
    "autoHideMenuBar": true
  },
  "autocomplete-plus": {
    "confirmCompletion": "tab"
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-beautify, v0.28.17
atom-ctags, v4.4.0
atom-typescript, v7.9.0
atom-yeoman, v0.3.15
file-types, v0.5.1
java-importer, v1.4.1
json-schema, v0.1.15
language-batch, v0.3.3
language-docker, v1.1.3
language-htaccess, v0.1.1
language-json5, v1.1.0
language-pascal, v0.14.0
language-plantuml, v0.1.1
linter, v1.11.0
markdown-preview-pandoc, v0.0.14
omnisharp-atom, v0.25.10
php-debug, v0.1.3
plantuml-viewer, v0.7.0
tabs-to-spaces, v0.11.1
terminal-plus, v0.14.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by benogle** [comment]
Interesting, it thinks the pane item is an editor. I suppose we should be using a different heuristic to check if an editor.

**Comment by benogle** [comment]
cc @as-cii I think we pulled out the instanceof check and replaced with something else. Maybe we should use a different check?

**Comment by as-cii** [comment]
Good point, @benogle. I guess in this case we should check for all the methods we use, instead of `::getText` which has been implemented in that package as well.

I am on it.

**Comment by as-cii** [comment]
(I miss type systems so much in these cases :cry:)

**Comment by guinnsquirrel** [comment]
The rendered PlantUML image appears briefly, then the plugin crashes :(
