### ISSUE TITLE
Uncaught TypeError: this.editor.onDidChangeCursorPosition is not a function

### ISSUE THREAD

**Issue by dabing1022** [atom/autocomplete-plus#639]
```js
Uncaught TypeError: this.editor.onDidChangeCursorPosition is not a function

/Volumes/Work/software/atom/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:139
Hide Stack Trace
TypeError: this.editor.onDidChangeCursorPosition is not a function
    at AutocompleteManager.module.exports.AutocompleteManager.updateCurrentEditor (/Volumes/Work/software/atom/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:139:48)
    at /Volumes/Work/software/atom/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
    at Emitter.module.exports.Emitter.emit (/Volumes/Work/software/atom/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /Volumes/Work/software/atom/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
    at Pane.module.exports.Pane.observeActiveItem (/Volumes/Work/software/atom/Atom.app/Contents/Resources/app.asar/src/pane.js:196:7)
    at /Volumes/Work/software/atom/Atom.app/Contents/Resources/app.asar/src/pane-container.js:331:42
    at Emitter.module.exports.Emitter.emit (/Volumes/Work/software/atom/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at PaneContainer.module.exports.PaneContainer.setActivePane (/Volumes/Work/software/atom/Atom.app/Contents/Resources/app.asar/src/pane-container.js:196:22)
    at Pane.module.exports.Pane.activate (/Volumes/Work/software/atom/Atom.app/Contents/Resources/app.asar/src/pane.js:623:15)
    at space-pen-div.<anonymous> (/Users/Childhood/.atom/packages/plantuml-viewer/lib/plantuml-viewer-view.js:43:48)
    at space-pen-div.jQuery.event.dispatch (/Volumes/Work/software/atom/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Volumes/Work/software/atom/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by dabing1022** [comment]
-  OSX: EI Capitan
-  Atom: 1.3.1
-  AutoComplete-plus: 2.23.0

**Comment by qiansen1386** [comment]
When I use plantuml-viewer extension and drag the uml preview image in the right panel. This error will always be thrown.
I hope this can help you guys reproduce the error.
Thanks a lot for your excellent work :v:

**Comment by dabing1022** [comment]
Yes, the error will be thrown when I use plantuml-viewer too.

**Comment by rogerkk** [comment]
In case it's of any use, I'm seeing this too.

**Atom Version**: 1.2.4
**System**: Ubuntu 15.04
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.23.0

**Comment by lee-dohm** [comment]
@rogerkk You may want to update to the most recent version of Atom.

**Comment by rogerkk** [comment]
@lee-dohm Done! Still same error, though.
