### ISSUE TITLE
Uncaught TypeError: this.editor.getBuffer is not a function

### ISSUE THREAD

**Issue by bracoduvnjak** [atom/autocomplete-plus#646]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Microsoft Windows 8.1
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.23.0

### Stack Trace

Uncaught TypeError: this.editor.getBuffer is not a function

```
At C:\Users\DEBRA\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:116

TypeError: this.editor.getBuffer is not a function
  at AutocompleteManager.module.exports.AutocompleteManager.updateCurrentEditor (C:\Users\DEBRA\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:116:33)
  at C:\Users\DEBRA\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61
  at Emitter.module.exports.Emitter.emit (C:\Users\DEBRA\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at C:\Users\DEBRA\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane-container.js:333:27
  at Emitter.module.exports.Emitter.emit (C:\Users\DEBRA\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\DEBRA\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:248:22)
  at Pane.module.exports.Pane.addItem (C:\Users\DEBRA\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:350:14)
  at Object.module.exports.FileBrowser.open (C:\Users\DEBRA\.atom\packages\file-browser\lib\file-browser.coffee:59:30)
  at atom-workspace.subscriptions.add.atom.commands.add.file-browser:open (C:\Users\DEBRA\.atom\packages\file-browser\lib\file-browser.coffee:35:85)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\DEBRA\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:260:29)
  at C:\Users\DEBRA\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\DEBRA\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\DEBRA\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\DEBRA\AppData\Local\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:97:36)
  at HTMLDocument.<anonymous> (C:\Users\DEBRA\AppData\Local\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:3:61)

```

### Commands

```
     -2:30 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:39.1.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:26 tree-view:toggle-side (atom-text-editor.editor.mini.is-focused)
  2x -0:29.6.0 file-browser:open (div.panels)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
file-browser, v0.4.1
language-ogre-script, v0.5.0
language-shadercode-shaderlab, v2.0.1
nuclide-toolbar, v0.0.35
tool-bar, v0.1.9
toolbar-iconshortcuts, v1.0.0

# Dev
No dev packages
```

**Comment by mario-areias** [comment]
+1 Got the same issue here

**Comment by Aerijo** [comment]
@dwy189 Can’t work around something you don’t know the cause of. That would need to be found first.
