### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rbottema** [atom/autocomplete-plus#679]
[Enter steps to reproduce below:]

1. Build Atom from master
2. Paste 260k lines of data (a simple English sentence repeated) in a new file

**Atom Version**: 1.7.0-dev-ff0942d
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.29.0

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At C:\Studie\atom\out\Atom\resources\app.asar\node_modules\autocomplete-plus\lib\symbol-store.js:158

RangeError: Maximum call stack size exceeded
    at SymbolStore.recomputeSymbolsForEditorInBufferRange (C:\Studie\atom\out\Atom\resources\app.asar\node_modules\autocomplete-plus\lib\symbol-store.js:158:74)
    at C:\Studie\atom\out\Atom\resources\app.asar\node_modules\autocomplete-plus\lib\symbol-provider.js:152:51
    at Function.module.exports.Emitter.simpleDispatch (C:\Studie\atom\out\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Studie\atom\out\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Studie\atom\out\Atom\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1345:25
```

### Commands

```
     -0:35.8.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```
---

When testing atom/atom#10855 on the newest build, I got this error. This did not happen on v1.5.3 or v1.6.0-beta5.

In other tests (same steps) I got an out of memory error in the console I opened safe Atom with:
```
[5060:0226/222044:FATAL:memory_win.cc(38)] Out of memory, size = 142618576
Backtrace:
        (No symbol) [0x00EDDA47]
        (No symbol) [0x00ED7F87]
        GetHandleVerifier [0x00F39CAE+188286]
        callnewh [0x1002B3BE+24]
        fcloseall [0x1000DBEC+34994]
        (No symbol) [0x00EFCA87]
        (No symbol) [0x00EFCB49]
        (No symbol) [0x00EFCBFA]
        icu_54::TimeZone::setID [0x014D574A+4436234]
        icu_54::TimeZone::setID [0x014D603C+4438524]
        icu_54::TimeZone::setID [0x014931A3+4164451]
        icu_54::TimeZone::setID [0x01415C16+3651030]
        icu_54::MessagePattern::partSubstringMatches [0x031E623B+3367803]
        icu_54::MessagePattern::partSubstringMatches [0x0322ED45+3665541]
        icu_54::RuleBasedBreakIterator::operator!= [0x01BF29E5+4899205]
        icu_54::RuleBasedBreakIterator::operator!= [0x01BF22DC+4897404]
        icu_54::RuleBasedBreakIterator::operator!= [0x01BF2397+4897591]
        icu_54::RuleBasedBreakIterator::operator!= [0x01C5F461+5344257]
        icu_54::RuleBasedBreakIterator::operator!= [0x01C591F6+5319062]
        v8::TypeSwitch::match [0x0F94A96E+651326]
        v8::Locker::IsLocked [0x0F839D1C+804588]
        v8::Locker::IsLocked [0x0F83C9CD+816029]
```
Even though Atom was using only 800MB of RAM at the time it gave the error and I had plenty free (>4GB). The data I'm pasting is 'only' 16MB large.

**Comment by benogle** [comment]
cc @as-cii 

Thanks for the report.

**Comment by rbottema** [comment]
Thanks for solving the issue! I'm still getting the out of memory errors, but I'm not sure if it's related to autocomplete-plus. Should I open a new issue in the atom repository?

**Comment by as-cii** [comment]
Does the exception you are getting here have the same stack trace? e.g.

```
RangeError: Maximum call stack size exceeded
    at SymbolStore.recomputeSymbolsForEditorInBufferRange (C:\Studie\atom\out\Atom\resources\app.asar\node_modules\autocomplete-plus\lib\symbol-store.js:158:74)
    at C:\Studie\atom\out\Atom\resources\app.asar\node_modules\autocomplete-plus\lib\symbol-provider.js:152:51
    at Function.module.exports.Emitter.simpleDispatch (C:\Studie\atom\out\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Studie\atom\out\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Studie\atom\out\Atom\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1345:25
```

Also, did you make sure to recompile Atom with the latest package dependencies?

Thanks!

**Comment by rbottema** [comment]
I ran `script/clean` and then `script/build` on the latest master branch of the Atom repo. `atom -v` reports `1.7.0-dev-1043dc0` as the Atom version, and so does 'About Atom'. I run Atom with `atom --safe`. I copy a large amount of data (the same data as before, 260k lines with 63 ASCII characters each) in Atom. Pasting takes a few seconds, but all the data shows up. Atom crashes immediately after, sometimes after about 10 seconds. I get the following error in console:
```
[11956:0304/130142:FATAL:memory_win.cc(38)] Out of memory, size = 71361360
Backtrace:
        (No symbol) [0x0023DA47]
        (No symbol) [0x00237F87]
        GetHandleVerifier [0x00299CAE+188286]
        callnewh [0x703FB3BE+24]
        fcloseall [0x703DDBEC+34994]
        (No symbol) [0x0025CA87]
        (No symbol) [0x0025CB49]
        (No symbol) [0x0025CC37]
        icu_54::TimeZone::setID [0x007F318F+4164431]
        icu_54::TimeZone::setID [0x00775C16+3651030]
        icu_54::MessagePattern::partSubstringMatches [0x0254623B+3367803]
        icu_54::MessagePattern::partSubstringMatches [0x0258ED45+3665541]
        icu_54::RuleBasedBreakIterator::operator!= [0x00F529E5+4899205]
        icu_54::RuleBasedBreakIterator::operator!= [0x00F522DC+4897404]
        icu_54::RuleBasedBreakIterator::operator!= [0x00F52397+4897591]
        icu_54::RuleBasedBreakIterator::operator!= [0x00FBF461+5344257]
        icu_54::RuleBasedBreakIterator::operator!= [0x00FB91F6+5319062]
        v8::TypeSwitch::match [0x5614A96E+651326]
        v8::Locker::IsLocked [0x56039D1C+804588]
        v8::Locker::IsLocked [0x5603C9CD+816029]
```

**Comment by as-cii** [comment]
This new error doesn't seem to be related to autocomplete-plus, as I would have expected a managed error rather than a hard crash. It has, however, definitely something to do with the large amount of text being pasted, and `RuleBasedBreakIterator` would lead me to think it's related to the tokenization process.

Can you reproduce it on stable? If yes, does it happen on safe mode (`atom --safe`) as well?

Thank you!

**Comment by rbottema** [comment]
I can reproduce the issue on 1.5.4, so that means it's not related to this issue. Where should I report it so it's most useful to you? Do you need more information from me?

**Comment by as-cii** [comment]
I think this should go under [atom/atom](https://github.com/atom/atom), but first make sure to perform a cursory search to check whether a similar issue has been reported already.

Thanks again for your precious :sparkles: help to track down this autocomplete-plus bug :bug:!

**Comment by bsr203** [comment]
just had this with the latest ATOM. the file opened was large json file.


[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.9.5
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package 2.34.2


### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:357

RangeError: Maximum call stack size exceeded
  at spliceWithArray (/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:357:37)
  at SymbolStore.recomputeSymbolsForEditorInBufferRange (/app.asar/node_modules/autocomplete-plus/lib/symbol-store.js:171:43)
  at /app.asar/node_modules/autocomplete-plus/lib/symbol-provider.js:425:37
  at /app.asar/node_modules/underscore/underscore.js:666:47

```

### Commands

```
     -8:08.1.0 core:undo (input.hidden-input)
     -8:07.2.0 core:redo (input.hidden-input)
     -7:10.2.0 find-and-replace:show (input.hidden-input)
  2x -7:10 core:confirm (input.hidden-input)
     -6:13.4.0 find-and-replace:show (input.hidden-input)
     -6:13.1.0 core:confirm (input.hidden-input)
     -6:11.2.0 find-and-replace:show-previous (input.hidden-input)
  2x -6:09.5.0 core:confirm (input.hidden-input)
     -1:05.1.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
autocomplete-paths 1.0.5 
file-icons 2.0.15 
fold-comments 0.6.0 
go-debug 1.0.4 
go-plus 5.1.1 
highlight-selected 0.12.0 
isotope-ui 2.7.1 
language-babel 2.54.1 
lcov-info 0.12.0 
linter 1.11.21 
linter-eslint 8.1.0 
merge-conflicts 1.4.4 
nuclide 0.205.0 
nuclide-format-js 0.0.36 
prettier-atom 0.16.0 
project-manager 3.3.3 
sort-lines 0.14.0 
terminal-plus 0.14.5 
tool-bar 1.0.1 
```

**Comment by octoquad** [comment]
Opened [composer.phar](https://getcomposer.org/download/) file by accident

1. Waited a few seconds for the atom to render the file
2. File was rendered but this error was present after it had loaded.

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Ubuntu 17.04
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package 2.35.3


### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /home/andrei/atom-1.11.1/out/app/node_modules/tree-view/lib/file.coffee:13466

RangeError: Maximum call stack size exceeded
    at spliceWithArray (/opt/atom/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:357:1)
    at SymbolStore.recomputeSymbolsForEditorInBufferRange (/opt/atom/resources/app/node_modules/autocomplete-plus/lib/symbol-store.js:171:1)
    at /opt/atom/resources/app/node_modules/autocomplete-plus/lib/symbol-provider.js:429:1
    at /opt/atom/resources/app/node_modules/underscore/underscore.js:666:1
```

### Commands

```
```

### Non-Core Packages

```
alignment 1.1.5 
atom-beautify 0.29.26 
autocomplete-html-entities 0.1.0 
blade-spacer 0.4.2 
busy-signal 1.4.3 
color-picker 2.2.5 
composer 0.5.0 
docblockr 0.10.3 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.7 
highlight-selected 0.13.1 
hyperclick 0.0.40 
indent-guide-improved 1.4.12 
intentions 1.1.2 
intentions-colorpicker 1.0.1 
intentions-numbers 1.0.4 
language-apache 1.7.0 
language-blade 0.30.0 
language-env 0.2.0 
language-ignore 1.5.2 
language-ini 1.19.0 
language-restructuredtext 1.1.0 
language-textile 0.2.0 
language-vb 0.1.0-pre1 
language-vue 0.23.0 
laravel 0.7.1 
linter 2.1.4 
linter-csslint 1.3.4 
linter-jshint 3.1.2 
linter-phpcs 1.6.4 
linter-scss-lint 3.1.0 
linter-shellcheck 1.4.4 
linter-ui-default 1.6.0 
markdown-writer 2.6.5 
minimap 4.28.2 
package-sync 1.1.0 
php-integrator-annotations 1.1.1 
php-integrator-autocomplete-plus 1.5.0 
php-integrator-base 2.1.12 
php-integrator-call-tips 1.2.1 
php-integrator-linter 1.3.0 
php-integrator-navigation 1.1.2 
php-integrator-refactoring 1.3.1 
php-integrator-tooltips 1.1.5 
pigments 0.39.1 
print-atom 0.1.1 
project-manager 3.3.5 
rest-client 1.3.1 
scroll-sync 0.1.5 
sort-lines 0.14.0 
tabs-to-spaces 1.0.3 
todo 0.6.0 
toggle-quotes 1.0.1 
vue-autocomplete 0.1.1 
vue2-autocomplete 0.1.0-alpha.4 
```

Is the path above `/home/andrei/atom-1.11.1/out/app/node_modules/tree-view/lib/file.coffee:13466` correct? I don't have a `/home/andrei/` at all. :)
