### ISSUE TITLE
autocomplete-manager.coffee:133 as TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by zhengchunxi** [atom/autocomplete-plus#682]
/Users/spring/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:133
Hide Stack Trace
TypeError: Cannot read property 'length' of undefined
    at /Users/spring/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:133:7
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:605:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:141:21)
    at AutocompleteManager.module.exports.AutocompleteManager.handleEvents (/Users/spring/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:131:36)
    at AutocompleteManager.handleEvents (/Users/spring/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1)
    at new AutocompleteManager (/Users/spring/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:55:6)
    at Object.module.exports.getAutocompleteManager (/Users/spring/.atom/packages/autocomplete-plus/lib/main.coffee:29:34)
    at Immediate._onImmediate (/Users/spring/.atom/packages/autocomplete-plus/lib/main.coffee:23:32)
    at processImmediate [as _immediateCallback] (timers.js:374:17)

**Comment by lee-dohm** [comment]
It looks like you have a separate installation of `autocomplete-plus` installed. Please uninstall the copy of autocomplete-plus you have in your `~/.atom/packages` directory. That should fix the problem.
