### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mateuswetah** [atom/autocomplete-plus#689]
[Enter steps to reproduce below:]

1. On Atom load having the autocomplete-plus installed or any other plugin that makes use of it.

**Atom Version**: 0.194.0
**System**: linux 4.2.0-34-generic
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.29.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/mateus/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:133

TypeError: Cannot read property 'length' of undefined
  at /home/mateus/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:133:7
  at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app.asar/src/config.js:555:7)
  at Config.module.exports.Config.observe (/usr/share/atom/resources/app.asar/src/config.js:135:21)
  at AutocompleteManager.module.exports.AutocompleteManager.handleEvents (/home/mateus/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:131:36)
  at AutocompleteManager.handleEvents (/home/mateus/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1)
  at new AutocompleteManager (/home/mateus/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:55:6)
  at Object.module.exports.getAutocompleteManager (/home/mateus/.atom/packages/autocomplete-plus/lib/main.coffee:29:34)
  at Immediate._onImmediate (/home/mateus/.atom/packages/autocomplete-plus/lib/main.coffee:23:32)
  at processImmediate [as _immediateCallback] (timers.js:369:17)

```

### Commands

```
     -9:55.3.0 settings-view:open (atom-text-editor.editor)
     -1:01.2.0 core:confirm (atom-text-editor.editor.mini)
 11x -0:47.3.0 core:backspace (atom-text-editor.editor.mini)
     -0:34.5.0 core:confirm (atom-text-editor.editor.mini)
     -0:03.6.0 core:cancel (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "oceanic-next"
    ],
    "disabledPackages": [
      "ionic-atom",
      "autocomplete-ionic-framework"
    ]
  },
  "autocomplete-plus": {}
}
```

### Installed Packages

```coffee
# User
angular2-snippets, v0.3.0
atom-ternjs, v0.13.2
autocomplete-ionic2-framework, v0.3.2
autocomplete-plus, v2.29.1
hidpi, v0.11.0
oceanic-next, v0.1.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
@mateuswetah if you edit `~/.atom/config.cson` to remove the empty `autocomplete-plus` section does that fix your issue?

**Comment by mateuswetah** [comment]
Hi @50Wliu. I upgraded Atom two days ago and the issue seems to be solved. I think we can close this.Thanks for the support!
