### ISSUE TITLE
Error On Install Manually

### ISSUE THREAD

**Issue by QVMaster** [atom/autocomplete-plus#750]
I'v got this error when installed manually on Atom:

```
Uncaught Error: Cannot find module 'semver'
module.js:341
Hide Stack Trace
Error: Cannot find module 'semver'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\VMaster\AppData\Local\atom\app-1.9.9\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\VMaster\AppData\Local\atom\app-1.9.9\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/VMaster/.atom/packages/autocomplete-plus-master/lib/autocomplete-manager.coffee:3:10)
    at Object.<anonymous> (file:///C:/Users/VMaster/.atom/packages/autocomplete-plus-master/lib/autocomplete-manager.coffee:1:1)
    at Module._compile (C:\Users\VMaster\AppData\Local\atom\app-1.9.9\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\VMaster\AppData\Local\atom\app-1.9.9\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\VMaster\AppData\Local\atom\app-1.9.9\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.module.exports.getAutocompleteManager (file:///C:/Users/VMaster/.atom/packages/autocomplete-plus-master/lib/main.coffee:28:29)
    at Immediate._onImmediate (file:///C:/Users/VMaster/.atom/packages/autocomplete-plus-master/lib/main.coffee:23:32)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)


```

**Comment by 50Wliu** [comment]
This package is not intended to be installed manually.  However, if you insist on doing so, be sure to run the `apm install` command.  In addition, if something goes wrong with the manually installed version don't expect any support.

**Comment by QVMaster** [comment]
I found it, in new version we don't need to install this package, Thanks man.
