### ISSUE TITLE
Uncaught TypeError: _suggestionListElement2.default is not a constructor

### ISSUE THREAD

**Issue by jarcos** [atom/autocomplete-plus#797]
[Enter steps to reproduce below:]

1. Create a MarkDown file
2. Write something in the file

**Atom Version**: 1.12.5
**Electron Version**: 1.3.9
**System**: Mac OS X 10.12.1
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.34.0

### Stack Trace

Uncaught TypeError: _suggestionListElement2.default is not a constructor

```
At /Users/josearcos/.atom/packages/autocomplete-plus/lib/autocomplete-manager.js:65

TypeError: _suggestionListElement2.default is not a constructor
    at Object.createView (/Users/josearcos/.atom/packages/autocomplete-plus/lib/autocomplete-manager.js:65:14)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:117:78)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:84:21)
    at OverlayManager.module.exports.OverlayManager.renderOverlay (/Applications/Atom.app/Contents/Resources/app.asar/src/overlay-manager.js:64:29)
    at OverlayManager.module.exports.OverlayManager.render (/Applications/Atom.app/Contents/Resources/app.asar/src/overlay-manager.js:18:16)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:250:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:323:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:219:9)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:59
```

### Commands

```
     -0:27.6.0 command-palette:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:24.9.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.mini.is-focused)
     -0:21.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:21.4.0 autocomplete-plus:activate (atom-text-editor.editor.vim-mode.insert-mode)
  3x -0:15.3.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/josearcos/Code",
    "telemetryConsent": "limited",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-dark"
    ],
    "useCustomTitleBar": true
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
atom-autocomplete-php, v0.20.2 (active)
atom-beautify, v0.29.13 (active)
atom-csscomb, v2.0.4 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (active)
atom-material-ui, v1.3.6 (active)
auto-update-packages, v1.0.1 (active)
autoclose-html, v0.23.0 (active)
autocomplete-modules, v1.6.7 (active)
autocomplete-plus, v2.34.0 (active)
autocomplete-wordpress-hooks, v0.2.2 (active)
build, v0.67.0 (active)
busy, v0.7.0 (active)
color-picker, v2.2.3 (active)
custom-title, v1.0.1 (active)
docblockr, v0.8.7 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.25 (active)
git-plus, v5.25.4 (active)
highlight-selected, v0.11.2 (active)
language-babel, v2.48.5 (active)
language-php, v0.37.3 (active)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (active)
linter-htmlhint, v1.3.1 (active)
linter-jshint, v3.0.1 (active)
linter-jsonlint, v1.3.0 (active)
linter-less, v2.6.0 (active)
linter-php, v1.3.1 (active)
linter-sass-lint, v1.7.4 (active)
linter-stylint, v2.2.5 (active)
linter-xmllint, v1.3.6 (active)
livestyle-atom, v0.2.7 (active)
markdown-writer, v2.6.2 (active)
merge-conflicts, v1.4.4 (active)
metrics, v1.1.2 (active)
minimap, v4.25.6 (active)
minimap-highlight-selected, v4.4.0 (active)
pigments, v0.37.0 (active)
pretty-json, v1.6.1 (active)
project-manager, v3.3.3 (active)
Remote-FTP, v0.9.4 (active)
script, v3.11.1 (inactive)
simple-drag-drop-text, v0.3.1 (active)
sort-lines, v0.14.0 (inactive)
terminal-plus, v0.14.5 (active)
todo-show, v1.8.0 (inactive)
vim-mode, v0.65.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.34.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please uninstall autocomplete-plus.  It isn't meant to be installed manually.

**Comment by jarcos** [comment]
@50Wliu do you mean to reinstall or just uninstall? If I uninstall I couldn't use it, that not solve the problem...

**Comment by 50Wliu** [comment]
I meant to uninstall.
Atom ships its own version of autocomplete-plus which will automatically become active once you uninstall your version.

**Comment by jarcos** [comment]
@50Wliu it's from the build-in version where I reported the error. I can't uninstall it, just disable it:

<img width="910" alt="screenshot 2016-11-23 15 58 16" src="https://cloud.githubusercontent.com/assets/933995/20566581/dba1e95a-b195-11e6-9519-365424972977.png">

**Comment by 50Wliu** [comment]
Run `apm uninstall autocomplete-plus` from the terminal.
