### ISSUE TITLE
Uncaught TypeError: (0 , _typeHelpers.isFunction) is not a function

### ISSUE THREAD

**Issue by ylabs82** [atom/autocomplete-plus#815]
[Enter steps to reproduce below:]

When I launch atom, this error appears. No action needed to reproduce the error, only launch atom.

**Atom Version**: 1.13.0
**Electron Version**: 1.4.15
**System**: linux 4.8.13-1-ARCH
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.33.1

### Stack Trace

Uncaught TypeError: (0 , _typeHelpers.isFunction) is not a function

```
At /usr/lib/atom/node_modules/autocomplete-plus/lib/provider-manager.js:221

TypeError: (0 , _typeHelpers.isFunction) is not a function
    at ProviderManager.isValidProvider (/usr/lib/atom/node_modules/autocomplete-plus/lib/provider-manager.js:221:64)
    at ProviderManager.registerProvider (/usr/lib/atom/node_modules/autocomplete-plus/lib/provider-manager.js:331:17)
    at ProviderManager.toggleDefaultProvider (/usr/lib/atom/node_modules/autocomplete-plus/lib/provider-manager.js:196:49)
    at /usr/lib/atom/node_modules/autocomplete-plus/lib/provider-manager.js:62:20
    at Config.module.exports.Config.observeKeyPath (/usr/lib/atom/src/config.js:616:7)
    at Config.module.exports.Config.observe (/usr/lib/atom/src/config.js:141:21)
    at new ProviderManager (/usr/lib/atom/node_modules/autocomplete-plus/lib/provider-manager.js:61:40)
    at new AutocompleteManager (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:85:28)
    at Object.getAutocompleteManager (/usr/lib/atom/node_modules/autocomplete-plus/lib/main.js:48:34)
    at Immediate.<anonymous> (/usr/lib/atom/node_modules/autocomplete-plus/lib/main.js:37:23)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
     -0:00.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (inactive)
autocomplete-python, v1.8.27 (active)
autoprefixer, v3.6.0 (inactive)
file-icons, v2.0.12 (active)
git-plus, v7.2.0 (active)
language-kivy, v0.1.1 (inactive)
language-rust, v0.4.9 (inactive)
linter, v1.11.21 (active)
linter-flake8, v2.1.4 (inactive)
linter-javac, v1.9.4 (active)
linter-php, v1.3.1 (active)
linter-rust, v0.7.2 (active)
minimap, v4.26.7 (active)
processing, v0.13.0 (inactive)
processing-language, v0.2.0 (inactive)
project-manager, v3.3.3 (active)
racer, v0.20.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
> Electron Version: 1.4.15

Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You may want to subscribe to https://bugs.archlinux.org/task/50357 for updates.
