### ISSUE TITLE
autocomplete-plus-master error

### ISSUE THREAD

**Issue by Limhojun** [atom/autocomplete-plus#832]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package 2.35.0

### Stack Trace

Failed to activate the autocomplete-plus package

```
At Cannot find module 'semver'

Error: Cannot find module 'semver'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.15.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/autocomplete-plus-master/lib/autocomplete-manager.js:4:24)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/autocomplete-plus-master/lib/main.js:2:29)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
```

### Commands

```
     -2:01.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:01.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.3.0 
atom-beautify 0.29.17 
busy-signal 1.3.0 
emmet 2.4.3 
file-icons 2.1.1 
highlight-selected 0.11.2 
intentions 1.1.2 
jQuery 1.2.4 
linter 2.1.0 
linter-eslint 8.1.4 
linter-htmlhint 1.3.2 
linter-sass-lint 1.7.1 
linter-ui-default 1.2.1 
markdown-themeable-pdf 1.2.0 
my-package 0.0.0 
```

**Comment by 50Wliu** [comment]
Do not manually install or link core packages unless you know what you're doing.  You can fix this issue by running `apm unlink autocomplete-plus-master`.
