### ISSUE TITLE
Uncaught TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by jimtahu** [atom/autocomplete-plus#841]
[Enter steps to reproduce:]

1. Copy/ pasted doxygen header for a file
2. Copy/ pasted a file name from include directive
3. Removed .h extension, started typing a .cpp (I believe the . triggered an autocomplete)

**Atom**: 1.17.0-beta5 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package 2.35.3

### Stack Trace

Uncaught TypeError: Cannot match against 'undefined' or 'null'.

```
At C:\Users\shennum\AppData\Local\atom\app-1.17.0-beta5\resources\app\node_modules\autocomplete-plus\lib\suggestion-list-element.js:316

TypeError: Cannot match against 'undefined' or 'null'.
    at SuggestionListElement.scrollSelectedItemIntoView (~/AppData/Local/atom/app-1.17.0-beta5/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:316:1)
    at SuggestionListElement.renderSelectedItem (~/AppData/Local/atom/app-1.17.0-beta5/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:301:1)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.17.0-beta5/resources/app/src/view-registry.js:223:1)
    at ~/AppData/Local/atom/app-1.17.0-beta5/resources/app/src/view-registry.js:3:1
```

### Commands

```
  3x -1:25.5.0 intentions:highlight (input.hidden-input)
     -1:25 core:copy (input.hidden-input)
     -1:20.4.0 editor:move-to-first-character-of-line (input.hidden-input)
     -1:20.1.0 editor:newline (input.hidden-input)
     -1:19.9.0 core:move-up (input.hidden-input)
     -1:19.7.0 intentions:highlight (input.hidden-input)
     -1:19.6.0 core:paste (input.hidden-input)
     -1:19.4.0 core:save (input.hidden-input)
  3x -1:17.2.0 core:backspace (input.hidden-input)
     -1:16.2.0 intentions:highlight (input.hidden-input)
     -1:16.2.0 core:save (input.hidden-input)
     -1:14.5.0 intentions:highlight (input.hidden-input)
     -1:14.5.0 core:save (input.hidden-input)
     -1:12.6.0 editor:newline (input.hidden-input)
     -1:11.9.0 intentions:highlight (input.hidden-input)
     -1:11.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
an-old-hope-syntax 1.0.4 
atom-build-waf 0.2.0 
atom-ctags 5.0.0 
atom-json-editor 0.4.1 
atom-material-syntax 1.0.3 
build 0.67.0 
busy 0.7.0 
busy-signal 1.4.1 
ctags-status 1.3.7 
file-watcher 1.1.0 
git-diff-details 1.4.0 
git-history 3.3.0 
git-plus 7.8.0 
git-time-machine 1.5.9 
greppen-grok 0.2.1 
hey-pane 0.3.1 
highlight-selected 0.13.1 
intentions 1.1.2 
language-diff 0.7.0 
language-doxygen 0.2.1 
language-lson 1.0.11 
language-lua 0.9.11 
linter 2.1.4 
linter-cppcheck 0.2.3 
linter-shellcheck 1.4.4 
linter-ui-default 1.3.0 
merge-conflicts 1.4.4 
minimap 4.28.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
octocat-syntax 1.3.1 
quick-highlight 0.10.0 
robin-hood-syntax 1.0.0 
symbols-tree-view 0.14.0 
trailing-spaces 0.4.0 
xml-tools 0.2.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you share more specific details for your steps to reproduce?  I'm not familiar with doxygen so if you can share more details like an example of exact text to copy and paste in your steps 1 and 2, that would be helpful so I can try and reproduce.

Also, for your step 3:

> 3. Removed .h extension, started typing a .cpp (I believe the . triggered an autocomplete)

Can you share a GIF or screencast that shows what you're doing here?

**Comment by jimtahu** [comment]
Hi rsese! I am traveling, and cannot attempt this on the original workstation. I have not seen this happen more than once.
The pasted text was similar to: 

//! @file OtherClass.h
//! words about this file and why it exists

There is a class MainClass in MainClass.h. After pasting into MainClass.cpp, I then copied "MainClass.h" from an
#include "MainClass.h"
pasted that, and then went to change it to MainClass.cpp

I hope that helps!
