### ISSUE TITLE
Uncaught TypeError: decorationIterator.getCloseScopeIds is not a function

### ISSUE THREAD

**Issue by tyrollins** [atom/autocomplete-plus#843]
**Version:**  1.18.0-dev-eea036750
**Machine:**  macOS 10.12.4
**Problem:** New build of Atom, got an the following error on first load. 
`Uncaught TypeError: decorationIterator.getCloseScopeIds is not a function`

/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:213
### Stack Trace 
```
TypeError: decorationIterator.getCloseScopeIds is not a function
    at ScreenLineBuilder.emitDecorationBoundaries (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:213:1)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:121:1)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:630:1)
    at TextEditorPresenter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:1371:1)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateLines (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:1378:1)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:123:1)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:266:1)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:198:1)
    at new TextEditorComponent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:172:1)
    at atom-text-editor.TextEditorElement.mountComponent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:203:24)
    at atom-text-editor.TextEditorElement.setModel (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:147:12)
    at atom-text-editor.TextEditorElement.initialize (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:133:12)
    at TextEditor.module.exports.TextEditor.getElement (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3332:1)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:100:1)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:88:1)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:205:1
    at Set.forEach (native)
    at TextEditorRegistry.observe (/Applications/Atom.app/Contents/Resources/app/src/text-editor-registry.js:170:1)
    at AutocompleteManager.handleEvents (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:204:1)
    at new AutocompleteManager (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:106:1)
    at Object.getAutocompleteManager (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:45:1)
    at Immediate.setImmediate (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:35:1)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by tyrollins** [comment]
Appears I was a little quick on the issue trigger, as this error is appearing for multiple packages, might be a hiccup atom/atom. 

Closing...
