### ISSUE TITLE
Uncaught Error: Cannot find module '../node_modules/minimatch/minimatch.js'

### ISSUE THREAD

**Issue by bishals** [atom/autocomplete-plus#857]
What error is this in my atom text editor?[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package 2.35.3

### Stack Trace

Uncaught Error: Cannot find module '../node_modules/minimatch/minimatch.js'

```
At module.js:457

Error: Cannot find module '../node_modules/minimatch/minimatch.js'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/app/src/module-cache.js:354:1)
    at Module.require (~/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.17.2/resources/app/static/<embedded>:73:1)
    at AutocompleteManager.isCurrentFileBlackListed (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:712:1)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:290:1)
```

### Commands

```
  3x -3:49.7.0 editor:newline (input.hidden-input)
     -3:28.8.0 core:backspace (input.hidden-input)
     -2:34.7.0 core:save (input.hidden-input)
     -2:20.5.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -2:13.1.0 core:backspace (input.hidden-input)
     -2:09.4.0 core:confirm (input.hidden-input)
  3x -1:59.4.0 core:backspace (input.hidden-input)
     -1:50.1.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -1:50.1.0 editor:newline (input.hidden-input)
  7x -1:43.3.0 core:backspace (input.hidden-input)
     -1:35.9.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -1:35.9.0 editor:newline (input.hidden-input)
  7x -1:21.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-bootstrap3 1.2.12 
atom-jade 0.3.0 
atom-material-ui 1.3.9 
autocomplete-ruby 0.2.5 
block-cursor 0.13.1 
emmet 2.4.3 
minimap 4.26.7 
pigments 0.39.0 
script 3.14.1 
set-syntax 0.3.2 
spacegray-atom-dark-syntax 1.3.2 
vim-mode 0.66.0 
```

**Comment by rsese** [comment]
We've had a few reports of missing files recently, can you try re-installing and let us know if you still get the same error?
