### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offsetHeight' of undefined

### ISSUE THREAD

**Issue by sheriffolaoye** [atom/autocomplete-plus#871]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 17.04
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package 2.35.4

### Stack Trace

Uncaught TypeError: Cannot read property 'offsetHeight' of undefined

```
At /home/andrei/atom-1.11.1/out/app/node_modules/tree-view/lib/file.coffee:158586

TypeError: Cannot read property 'offsetHeight' of undefined
    at SuggestionListElement.readUIPropsFromDOM (/opt/atom/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:337:54)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/opt/atom/resources/app/src/view-registry.js:227:15)
    at /opt/atom/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -0:29.9.0 core:move-down (input.hidden-input)
     -0:29.2.0 core:select-page-down (input.hidden-input)
     -0:24.2.0 editor:toggle-line-comments (input.hidden-input)
     -0:19.6.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
platformio-ide-terminal 2.5.3 
```

**Comment by lightspread** [comment]
Wrtie Chinese in markdown editor also got such error . 
```
/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:337
Hide Stack Trace
TypeError: Cannot read property 'offsetHeight' of undefined
    at SuggestionListElement.readUIPropsFromDOM (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:337:54)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:191:15)
    at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:65
```

**Comment by James-Matthew** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 7 Home Premium 
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package 2.35.7


### Stack Trace

Uncaught TypeError: Cannot read property 'offsetHeight' of undefined

```
At C:\Users\operator\AppData\Local\atom\app-1.20.1\resources\app\node_modules\autocomplete-plus\lib\suggestion-list-element.js:337

TypeError: Cannot read property 'offsetHeight' of undefined
    at SuggestionListElement.readUIPropsFromDOM (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:337:54)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.20.1/resources/app/src/view-registry.js:191:15)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -7:15.1.0 core:paste (div.line.cursor-line)
     -7:06.2.0 core:copy (span.hard-tab.leading-whitespace)
     -7:02.1.0 editor:newline (input.hidden-input)
     -6:58 core:paste (div.line.cursor-line)
     -6:51.7.0 core:save (input.hidden-input)
     -6:07.4.0 core:copy (span.syntax--text.syntax--plain.syntax--null-grammar)
     -6:03.9.0 editor:newline (input.hidden-input)
     -6:00.8.0 core:paste (div.line.cursor-line)
     -5:53.2.0 core:copy (span.hard-tab.leading-whitespace)
     -5:47.4.0 editor:newline (input.hidden-input)
     -5:43.2.0 core:paste (div.line.cursor-line)
     -5:37.8.0 core:save (input.hidden-input)
     -4:54.7.0 core:move-left (input.hidden-input)
     -4:52.7.0 core:backspace (input.hidden-input)
  2x -4:51.8.0 core:move-left (input.hidden-input)
  7x -4:50.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by SHA-256** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 ia32
**Electron**: 1.6.9
**OS**: Haiku OS
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package 2.35.5


### Stack Trace

Uncaught TypeError: Cannot read property 'offsetHeight' of undefined

```
At ~\AppData\Local\atom\app-1.19.0\resources\app\node_modules\autocomplete-plus\lib\suggestion-list-element.js:337

TypeError: Cannot read property 'offsetHeight' of undefined
    at SuggestionListElement.readUIPropsFromDOM (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:337:54)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.19.0/resources/app/src/view-registry.js:191:15)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -1:13.5.0 docblockr:parse-enter (input.hidden-input)
     -1:13.5.0 editor:newline (input.hidden-input)
     -1:13.3.0 docblockr:parse-enter (input.hidden-input)
     -1:13.3.0 editor:newline (input.hidden-input)
     -1:13 core:paste (input.hidden-input)
  2x -1:12.3.0 core:save (input.hidden-input)
  2x -1:06.6.0 core:backspace (input.hidden-input)
     -1:05.6.0 core:save (input.hidden-input)
     -1:04.2.0 core:copy (input.hidden-input)
     -1:02.1.0 core:paste (input.hidden-input)
  2x -1:01.7.0 core:save (input.hidden-input)
     -0:56.3.0 core:copy (input.hidden-input)
     -0:55.1.0 core:paste (input.hidden-input)
     -0:54.4.0 core:save (input.hidden-input)
     -0:53.5.0 core:paste (input.hidden-input)
     -0:51.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
docblockr 0.11.0 
file-icons 2.1.10 
minimap 4.29.6 
pigments 0.40.2 
```
