### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /^ (;;/: Unterminated group

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/autocomplete-plus#898]
1. Set the default provider to `Subsequence` in the `autocomplete-plus` settings
1. Open a JavaScript file
1. Type `for (;;`

/cc @leroix - This looks like an issue with the `strictMatchRegex`. Do we even need a RegExp for this purpose or can we just use `match.word.includes(prefix)`?

**Atom**: 1.23.0-dev-34cd21d x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.11.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /^ (;;/: Unterminated group

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/subsequence-provider.js:157

SyntaxError: Invalid regular expression: /^ (;;/: Unterminated group
    at new RegExp (<anonymous>)
    at SubsequenceProvider.getSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/subsequence-provider.js:157:36)
    at providers.forEach.provider (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:262:21)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:254:23)
```

**Comment by leroix** [comment]
Thanks for the report! I'll get this fixed asap.
