### ISSUE TITLE
autocomplete-plus

### ISSUE THREAD

**Issue by Davidshb** [atom/autocomplete-plus#968]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package 2.40.5

### Stack Trace

Failed to activate the autocomplete-plus package

```
At Package not initialized

Error: Package not initialized
    at /packages/atom-ide-ui/modules/nuclide-commons-atom/createPackage.js:61:35)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:397:75)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:233:20)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at packagesToEnable.forEach.name (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:440:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:440:30)
    at emitter.on (/Applications/Atom.app/Contents/Resources/app/src/config.js:1067:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:1226:62)
    at Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:1052:23)
    at Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:715:18)
    at Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:905:16)
    at Package.enable (/Applications/Atom.app/Contents/Resources/app/src/package.js:75:30)
    at PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:246:18)
    at HTMLButtonElement.enablementButtonClickHandler (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:362:31)
```

### Commands

```
     -8:28.9.0 core:confirm (input.hidden-input)
     -8:08.1.0 editor:newline (input.hidden-input)
 13x -8:05.8.0 core:backspace (input.hidden-input)
  2x -6:07.0 core:confirm (input.hidden-input)
     -5:46.8.0 core:backspace (input.hidden-input)
  2x -5:46.5.0 core:confirm (input.hidden-input)
 18x -5:28.9.0 core:backspace (input.hidden-input)
     -4:36.7.0 editor:newline (input.hidden-input)
     -4:28.6.0 core:move-right (input.hidden-input)
     -4:26 core:save (input.hidden-input)
     -4:04.0 core:backspace (input.hidden-input)
     -4:03.1.0 core:undo (input.hidden-input)
  2x -4:00.6.0 core:backspace (input.hidden-input)
     -3:59.1.0 core:save (input.hidden-input)
  4x -1:56.5.0 core:backspace (input.hidden-input)
     -1:26.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-clock 0.1.16 
autocomplete-javascript 0.0.2 
autocomplete-sql 0.5.0 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
dracula-syntax 2.0.6 
dracula-ui 0.6.0 
isotope-ui 2.8.5 
```

### Versions

Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python 2.7.10
git 2.15.0

**Comment by Aerijo** [comment]
Am I missing something, or is the error referencing a non-core package
```
/packages/atom-ide-ui/modules/nuclide-commons-atom
```
Doesn't this indicate it's not in safe mode?

**Comment by Davidshb** [comment]
I don’t but it’s a core package that’s why it is difficult for me to solve
